//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется PosTerminal.rc
//
#define IDC_MYICON                      2
#define IDD_POSTERMINAL_DIALOG          102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_POSTERMINAL                 107
#define IDI_SMALL                       108
#define IDC_POSTERMINAL                 109
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_DIALOG2                     130
#define IDD_DIALOG3                     131
#define IDD_DIALOG4                     132
#define IDD_DIALOG5                     133
#define IDD_DIALOG6                     134
#define IDD_DIALOG7                     135
#define IDD_DIALOG8                     136
#define IDD_DIALOG9                     137
#define IDD_DIALOG10                    138
#define IDD_DIALOG11                    139
#define IDD_DIALOG12                    140
#define IDD_DIALOG13                    141
#define IDD_DIALOG14                    142
#define IDD_DIALOG15                    143
#define IDD_DIALOG16                    144
#define IDD_DIALOG17                    145
#define IDD_DIALOG18                    146
#define IDD_DIALOG19                    147
#define IDD_DIALOG20                    148
#define IDC_BUTTON1                     1000
#define IDC_BTN_SAVE_SAPP               1000
#define IDC_BTN_SAVE_ADDSAPP            1000
#define IDC_BTN_RESET                   1000
#define IDC_ADDCAT_BTN                  1000
#define IDC_BUTTON2                     1001
#define IDC_BTN_CANCEL_ADDSAPP          1001
#define IDC_BUTTON3                     1002
#define IDC_BTN_1                       1002
#define IDC_BUTTON4                     1003
#define IDC_EDIT1                       1003
#define IDC_BUTTON_Users                1003
#define IDC_BUTTON5                     1004
#define IDC_EDIT2                       1004
#define IDC_BTN_DEL_MOV                 1004
#define IDC_BUTTON6                     1005
#define IDC_EDIT3                       1005
#define IDC_BTN_CLOSE_MOV               1005
#define IDC_EDIT_LN_SAPP                1005
#define IDC_EDIT_PRODQUANTITY           1005
#define IDC_BUTTON7                     1006
#define IDC_COMBO2                      1006
#define IDC_EDIT4                       1006
#define IDC_BTN_MOVEMENT                1006
#define IDC_COMBO_LOCAT_TERM            1006
#define IDC_EDIT_MOB_SAPP               1006
#define IDC_BUTTON8                     1007
#define IDC_EDIT5                       1007
#define IDC_BTN_CLOSE_REC               1007
#define IDC_EDIT_MAIL_SAPP              1007
#define IDC_COMBO1                      1008
#define IDC_COMBO_ROLE_AD_USER          1008
#define IDC_COMBO4                      1009
#define IDC_EDIT10                      1009
#define IDC_EDIT_VISA_BALANCE_RP        1009
#define IDC_COMBO_STATUS_AD_USER        1009
#define IDC_COMBO_STATUS_AD_USER2       1010
#define IDC_SLIDER1                     1014
#define IDC_LIST2                       1015
#define IDC_LIST_USERS                  1015
#define IDC_COMBO3                      1016
#define IDC_COMBO_PAYMETH_TERM          1016
#define IDC_LIST1                       1019
#define IDC_LIST_TERM                   1019
#define IDC_EDIT6                       1020
#define IDC_EDIT_MAILCOM_SAPP           1020
#define IDC_EDIT7                       1021
#define IDC_EDIT_MOBCOMNUM_SUPP         1021
#define IDC_EDIT8                       1022
#define IDC_EDIT_ADRESSCOM_SAPP         1022
#define IDC_EDIT9                       1023
#define IDC_EDIT_JT_SAPP                1023
#define IDC_DATETIMEPICKER1             1024
#define IDC_DATETIMEPICKER_PW           1024
#define IDC_DATETIMEPICKER2             1025
#define IDC_DATETIMEPICKER_TO_MOV       1025
#define IDC_BUTTON11                    1029
#define IDC_BTN_4                       1029
#define IDC_BUTTON12                    1030
#define IDC_BTN_5                       1030
#define IDC_BUTTON9                     1031
#define IDC_BTN_2                       1031
#define IDC_BUTTON10                    1032
#define IDC_BTN_3                       1032
#define IDC_BTN_PRODCATEGORY            1032
#define IDC_BUTTON13                    1033
#define IDC_BTN_6                       1033
#define IDC_BUTTON14                    1034
#define IDC_BTN_7                       1034
#define IDC_BUTTON15                    1035
#define IDC_BTN_8                       1035
#define IDC_BUTTON16                    1036
#define IDC_BTN_9                       1036
#define IDC_BUTTON17                    1037
#define IDC_BTN_0                       1037
#define IDC_BUTTON18                    1038
#define IDC_BTN_DOT                     1038
#define IDC_BUTTON19                    1039
#define IDC_BTN_AC                      1039
#define IDC_BUTTON20                    1040
#define IDC_BTN_Del                     1040
#define IDC_BUTTON21                    1041
#define IDC_BTN_Close                   1041
#define IDC_Btn_Cancel                  1045
#define IDC_btn_Login                   1046
#define IDC_BUTTON_Terminal             1047
#define IDC_BUTTON_Client               1048
#define IDC_BUTTON_Product              1049
#define IDC_BUTTON_Pricing              1050
#define IDC_BUTTON_Location             1051
#define IDC_BUTTON_Supliers             1052
#define IDC_BUTTON_Reports              1053
#define IDC_BTN_Add_Product             1054
#define IDC_BTN_Pay                     1055
#define IDC_BTN_CloseP                  1056
#define IDC_BTN_DelP                    1057
#define IDC_BTN_EditP                   1058
#define IDC_BTN_Select                  1059
#define IDC_BTN_Category                1060
#define IDC_BTN_AddProdact1             1061
#define IDC_BTN_Close2                  1062
#define IDC_BTN_Del2                    1063
#define IDC_BTN_Edit2                   1064
#define IDC_BTN_Select2                 1065
#define IDC_BTN_AddUser                 1066
#define IDC_BTN_SKU                     1067
#define IDC_BTN_Select3                 1067
#define IDC_BTN_SELECT3                 1067
#define IDC_BTN_ADD3                    1068
#define IDC_BTN_CANCEL3                 1069
#define IDC_EDIT_SKU                    1070
#define IDC_EDIT_PRODNAME               1071
#define IDC_COMBO_CATEGORY              1072
#define IDC_EDIT_DESCRIPTION            1073
#define IDC_BTN_ADDLOCATION             1074
#define IDC_BTN_EDIT_LOC                1076
#define IDC_BTN_DEL_LOC                 1077
#define IDC_BTN_CLOSE_LOC               1078
#define IDC_EDIT_SERCH_LOC              1079
#define IDC_LIST_LOC                    1080
#define IDC_BTN_SELECT_PR               1081
#define IDC_BTN_APPLY1                  1082
#define IDC_BTN_APPLY2                  1083
#define IDC_BTN_SAVE_PRICE              1084
#define IDC_BTN_CLOSE_PR                1085
#define IDC_EDIT_SEARCH_PR              1086
#define IDC_COMBO_CATEG_PR              1087
#define IDC_COMBO_SORT_PR               1088
#define IDC_LIST_PR                     1089
#define IDC_EDIT_BASE_MARK              1090
#define IDC_EDIT_SET_PRISE              1091
#define IDC_EDIT_SEARCH_PRODUCT         1092
#define IDC_COMBO_CATEGORY_PRODUCT      1093
#define IDC_COMBO_LOCAT_PRODUC          1094
#define IDC_COMBO_SORT_PROD3            1095
#define IDC_LIST_PROD3                  1096
#define IDC_EDIT_SEARC_CL               1097
#define IDC_COMBO_SORT_CL               1098
#define IDC_BTN_ADD_CL                  1099
#define IDC_BTN_SELECT_CL               1100
#define IDC_BTN_EDIT_CL                 1101
#define IDC_BTN_DEL_CL                  1102
#define IDC_BTN_CLOSE_CL                1103
#define IDC_LIST_CLIENT                 1104
#define IDC_EDIT_SEARCH_SUP             1105
#define IDC_COMBO_SORT_SUP              1106
#define IDC_BTN_ADD_SUP                 1107
#define IDC_BTN_SELECT_SUP              1108
#define IDC_BTN_EDIT_SUP                1109
#define IDC_BTN_DEL_SUP                 1110
#define IDC_BTN_CLOSE_SUP               1111
#define IDC_LIST_SUP                    1112
#define IDC_COMBO_LOCATION_RP           1113
#define IDC_COMBO_TIPE_PAY_RP           1114
#define IDC_DATETIMEPICKER_fRP          1115
#define IDC_DATETIMEPICKER_tRP          1116
#define IDC_BTN_SELECT_RP               1117
#define IDC_EDIT_CASH_BALANCE_RP        1118
#define IDC_LIST_REPORT                 1119
#define IDC_EDIT_TOTAL_INCOME_RP        1120
#define IDC_EDIT_TOTAL_CASH_RP          1121
#define IDC_EDIT_TOTAL_VISA_RP          1122
#define IDC_EDIT_TOTAL_AMOUT_RP         1123
#define IDC_EDIT_TOTAL_EXPE_RP          1124
#define IDC_EDIT_TOTAL_EXPE_CASH_RP     1125
#define IDC_EDIT_TOTAL_EXPE_VISA_RP     1126
#define IDC_BTN_CLOSE_RP                1127
#define IDC_EDIT_LOC_NAME               1128
#define IDC_EDIT_LOC_ADRESS             1129
#define IDC_BTN_SAVE_NEW_LOC            1130
#define IDC_BTN_CANCEL_NLOC             1131
#define IDC_EDIT_SEARCH_MOV             1132
#define IDC_COMBO_SUPLI_MOV             1133
#define IDC_DATETIMEPICKER_FROM_MOV     1134
#define IDC_BTN_RECEIP_MOV              1135
#define IDC_BTN_SELECT_MOV              1136
#define IDC_BTN_EDIN_MOV                1137
#define IDC_LIST_MOVEMENT               1138
#define IDC_EDIT_IVOICENUM_REC          1139
#define IDC_EDIT_LOCAT_REC              1140
#define IDC_DATETIMEPICKER_REC          1141
#define IDC_COMBO_SUPLIER_REC           1142
#define IDC_LIST_REC                    1143
#define IDC_BTN_ADD_ITEM_REC            1144
#define IDC_BTN_DEL_ITEM_REC            1145
#define IDC_EDIT_QTY_REC                1146
#define IDC_EDIT_PRICE_REC              1147
#define IDC_BTN_APPLY_REC               1148
#define IDC_BTN_SAVE_REC                1149
#define IDC_EDIT_TOTAL_QTY_REC          1150
#define IDC_EDIT_TOTAL_AMOUNT_REC       1151
#define IDC_COMBO_PAY_TYPE_REC          1152
#define IDC_BTN_PAY_REC                 1153
#define IDC_EDIT_SEARCH_ADDPROD         1154
#define IDC_COMBO_CATEG_ADDPROD         1155
#define IDC_COMBO_SORT_ADDPROD          1156
#define IDC_BTN_SELECT_ADDPROD          1157
#define IDC_EDIT_QTY_ADDPROD            1158
#define IDC_BTN_ADD_ADDPROD             1159
#define IDC_BTN_CLOSE_ADDPROD           1160
#define IDC_LIST_ADDPROD                1161
#define IDC_COMBO_CLIENT_TERM           1162
#define IDC_EDIT_TOTAL_AMOU_TERM        1163
#define IDC_EDIT_DISCOUNT_TERM          1164
#define IDC_EDIT_TOTAL_WD_TERM          1165
#define IDC_EDIT_CALACWIN_TERM          1166
#define IDC_EDIT_INV_NUM_PW             1167
#define IDC_EDIT_TOTALAM_PW             1168
#define IDC_EDIT_TOTALDIS_PW            1169
#define IDC_EDIT_TOTALWDIC_PW           1170
#define IDC_COMBO_PAYMET_PW             1171
#define IDC_EDIT_RES_MON_PW             1172
#define IDC_EDIT_CANGE_PW               1173
#define IDC_EDIT_RESPONS_PW             1174
#define IDC_BTN_PAY_PW                  1175
#define IDC_BTN_CANCEL_PW               1176
#define IDC_EDIT_SEARCH_USER            1177
#define IDC_COMBO_ROLE_USER             1178
#define IDC_COMBO_STATUS_USER           1179
#define IDC_BTN_SAVE_USER               1180
#define IDC_SORT_BY_USER                1180
#define IDC_BTN_CANCEL_USER             1181
#define IDC_EDIT_FN_USER                1182
#define IDC_EDIT_LN_USER                1183
#define IDC_EDIT_MOB_USER               1184
#define IDC_EDIT_MAIL_AD_USER           1185
#define IDC_EDIT_PASS_USER              1186
#define IDC_EDIT_FN_CLIENT              1187
#define IDC_EDITLN_CLIENT               1188
#define IDC_BTN_CLEAR_USER              1188
#define IDC_EDIT_MOB_CLIENT             1189
#define IDC_BTN_SAVE_USER2              1189
#define IDC_BTN_GENERATE_PASSWORD       1189
#define IDC_EDIT_MAIL_CLIENT            1190
#define IDC_EDIT_DISC_CLIENT            1191
#define IDC_BTN_SAVE_ADDCLIENT          1192
#define IDC_BTN_CANCEL_ADDCLIENT        1193
#define IDC_EDIT_COMNAME_SUPPL          1194
#define IDC_EDIT_FN_SAPP                1195
#define IDC_LIST_PRODUCTS               1196
#define IDC_EDIT_INPRICE                1198
#define IDC_EDIT_OUTPRICE               1199
#define IDC_EDIT_ADDCAT                 1200
#define IDC_BTN_Select3                 1201
#define IDC_RESET_SORT_USER             1201
#define IDC_SORT_BY_USERS               1202
#define IDC_REDISPLAY_USERS             1203
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1204
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
